name: Cadence Integration Test
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  tests:
    name: "Integration testing with sticky cache disabled"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-subset:
          - "a-m"
          - "n-z"
    steps:
      - uses: actions/checkout@v3
      - name: "Set up cadence environment"
        run: docker compose -f docker-compose/ci-cadence-dependencies.yml up -d
      - name: "Test against cadence"
        run: make ci-cadence-integ-test-disable-sticky startsWith=${{ matrix['test-subset'] }}
      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
